apiVersion: v2
name: odoo
version: 0.4.0
kubeVersion: ">=1.26.0-0"
description: Production-ready Odoo with PostgreSQL, S3, and optional frontend
type: application
appVersion: "18.0"
home: https://github.com/bershadsky/helm
sources:
  - https://github.com/bershadsky/helm
maintainers:
  - name: Sergey Bershadsky
    email: sergio@djangoheads.com
    url: https://djangoheads.com
dependencies: []
