{{- if .Values.frontend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "odoo.fullname" . }}-frontend
  labels:
    {{- include "odoo.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  {{- with .Values.frontend.updateStrategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "odoo.frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "odoo.frontend.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "odoo.serviceAccountName" . }}
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.frontend.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          {{- with .Values.frontend.containerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.frontend.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.frontend.args }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.frontend.service.port }}
              protocol: TCP
          env:
            {{- range .Values.frontend.env }}
            - name: {{ .name }}
              {{- if hasPrefix "USE_TPL:" .value }}
              value: {{ tpl (trimPrefix "USE_TPL:" .value) $ | quote }}
              {{- else }}
              value: {{ .value | quote }}
              {{- end }}
            {{- end }}
          {{- if .Values.frontend.startupProbe.enabled }}
          startupProbe:
            httpGet:
              path: {{ .Values.frontend.startupProbe.path }}
              port: {{ .Values.frontend.startupProbe.port }}
            periodSeconds: {{ .Values.frontend.startupProbe.periodSeconds }}
            failureThreshold: {{ .Values.frontend.startupProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.frontend.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.frontend.livenessProbe.path }}
              port: {{ .Values.frontend.livenessProbe.port }}
            periodSeconds: {{ .Values.frontend.livenessProbe.periodSeconds }}
            failureThreshold: {{ .Values.frontend.livenessProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.frontend.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.frontend.readinessProbe.path }}
              port: {{ .Values.frontend.readinessProbe.port }}
            periodSeconds: {{ .Values.frontend.readinessProbe.periodSeconds }}
            failureThreshold: {{ .Values.frontend.readinessProbe.failureThreshold }}
          {{- end }}
          {{- with .Values.frontend.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.frontend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.frontend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.frontend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
