{{- if .Values.backend.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "odoo.fullname" . }}-backend
  labels:
    {{- include "odoo.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.backend.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "odoo.backend.selectorLabels" . | nindent 6 }}
{{- end }}
