{{- if .Values.nginx.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "odoo.nginx.serviceName" . }}
  labels:
    {{- include "odoo.labels" . | nindent 4 }}
    app.kubernetes.io/component: nginx
spec:
  type: {{ .Values.nginx.service.type }}
  ports:
    - port: {{ .Values.nginx.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "odoo.nginx.selectorLabels" . | nindent 4 }}
{{- end }}
