apiVersion: v1
kind: Service
metadata:
  name: {{ include "odoo.fullname" . }}-backend
  labels:
    {{- include "odoo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    {{- include "odoo.backend.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.backend.service.ports.http }}
      targetPort: http
      protocol: TCP
    - name: websocket
      port: {{ .Values.backend.service.ports.websocket }}
      targetPort: websocket
      protocol: TCP
